docs/contribute/overview.md
docs/embed/use-case/_category_.json
i18n/zh/docusaurus-plugin-content-docs/current/contribute/overview.md

This PR updates the contribution overview at https://wasmedge.org/docs/contribute/overview

[Feat] - Updated Contribution Overview

---

.github/ISSUE_TEMPLATE/doc.yaml
.github/PULL_REQUEST_TEMPLATE.md

Issue & PR template added

---

.github/workflows/deploy.yml
package-lock.json

https://github.com/WasmEdge/docs/issues/17 Added cache using github action<sup>[1]</sup>
1. https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

Add Caching Capabilities to Workflow [#17]

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
README.md

This PR,
- Updates the README.md
- Moved Contributing Flow to Separate File
- Added Code of Conduct

[Feat] - Update Contributing Doc, Readme and Add Code of Conduct

---

docusaurus.config.js
package-lock.json
package.json

This added search support to the docs using https://github.com/easyops-cn/docusaurus-search-local it can also be replace in future for Algolia or similar if needed.
Closes  [DOCS] Enable Search for the docs #28 
Additional features
Deployed version to test and preview: https://render.sahil.world/docs/

Added Search Feature

---

docusaurus.config.js

I made the sidebar collapsible, so users can focus better on the content.
Additional features

enable sidebar collapse feature

---

package-lock.json
package.json

This PR updates Docusaurus to v2.4.0

[Feat] - Updated Docusaurus to v2.4.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/user-feedback.yml

Added Bug Report, Feature Request and User Feedback Issue forms.

added 3 issue forms

---

docusaurus.config.js

This PR is address #46 issue please refer it for more info. 
It also restructures the footer and indication for external links.
Here is what changes Before/ After visuals
Link to preview the changes: https://render.sahil.world/docs/

Fix for build failing

---

.github/workflows/codeql-analysis.yml

This PR adds CodeQL Analysis workflow to the project
More Info: https://codeql.github.com/

[Feat] - Added CodeQL Analysis Workflow

---

.github/workflows/codeql-analysis.yml

The workflow file had issue with a event trigger, this PR fixes the same

[Bug] - Fixed Event Trigger Name

---

docs/develop/build-and-run/install.md
docs/develop/javascript/hello_world.md
docs/develop/javascript/tensorflow.md
docs/develop/rust/http_service/client.md

Add TLS and HTTPS support in the docs

Add TLS plugin

---

package-lock.json
package.json

Added 1e0a76042cbe6c216afda1a9143383eb39973bb9 which lead to build fail
Closes #78

Fixed Build Step

---

docs/embed/rust/intro.md

Fixes the issues related to the JSX syntax.
NA
Bug fix.
NA

[Bug] fix JSX issues

---

docs/contribute/source/plugin/wasi_nn.md
docs/start/install.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/source/plugin/wasi_nn.md
i18n/zh/docusaurus-plugin-content-docs/current/start/install.md

Updating docs for OpenVino (version 2023.0.0)

---

.github/workflows/deploy.yml

**Description**:
- This PR enables concurrency for deploy workflow for faster deployment

[Feat] - Enabled Concurrency for Deploy Workflow

---

docs/develop/rust/wasinn/mediapipe.md
docs/develop/rust/wasinn/pytorch.md
docs/develop/rust/wasinn/tensorflow_lite.md
docs/develop/rust/wasinn/tf_plugin.md
docs/embed/go/ai.md
docs/embed/go/intro.md
docs/start/install.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/plugin/develop_plugin_cpp.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/javascript/hello_world.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/javascript/networking.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/bindgen.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/command.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/dapr.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/database/_category_.json
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/http_service/client.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/http_service/server.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/socket_networking/client.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/socket_networking/server.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/ssr.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasicrypto.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasinn/_category_.json
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasinn/mediapipe.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasinn/openvino.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasinn/pytorch.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasinn/tensorflow_lite.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/wasinn/tf_plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/embed/go/ai.md
i18n/zh/docusaurus-plugin-content-docs/current/embed/go/intro.md
i18n/zh/docusaurus-plugin-content-docs/current/start/install.md

Fix the deleted WasmEdge-tensorflow plug-in related contents in #154 
The WasmEdge tensorflow plug-in is not related to the WASI-NN.
cc @juntao  @alabulei1

Fix deleted WasmEdge tensorflow plug-in

---

i18n/zh/docusaurus-plugin-content-docs/current/start/overview.md

…iew.md
Add zh-cn translation
N/A
Translate i18n/zh/docusaurus-plugin-content-docs/current/start/overview.md

translate i18n/zh/docusaurus-plugin-content-docs/current/start/overview.md

---

docs/contribute/plugin/develop_plugin_c.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/plugin/develop_plugin_c.md

Add missing command in C plugin guide
#199
/kind bug

Add missing command in C plugin guide

---

docs/develop/rust/database/my_sql_driver.md
docs/develop/rust/http_service/client.md

Add HTTPS section for reqwest and mysql_async

Update client.md for HTTPS in reqwest

---

docs/contribute/source/plugin/wasi_nn.md

Add docs for building ggml plugins.
Fixes #203 

Add building guide for the ggml plugin

---

docs/develop/deploy/cri-runtime/containerd.md
i18n/zh/docusaurus-plugin-content-docs/current/develop/deploy/cri-runtime/containerd.md

Complete the full steps with the latest runwasi.
[Twitter](https://twitter.com/ralph_squillace/status/1757734360520753246)
documentation
Missing content, as well as outdated steps.

Update the section about running a simple WASI app with runwasi

---

docs/contribute/users.md

Add users
None
Docs
Add a few more WasmEdge users and adaptors

Add more users

---

docs/start/build-and-run/aot.md

Fixed typo
