- docs/develop/deploy/use-case/kubedge.md
This PR does the following changes:
- modify all occurrences of k8s.gcr.io to registry.k8s.io.
This is a part of https://github.com/kubernetes/k8s.io/issues/4780.
> Migrate from k8s.gcr.io to registry.k8s.io

- docs/contribute/source/os/windows.md
I embedded links to the installation instructions for the required dependencies, in order to make them easier to install.
documentation
> embed links for installing dependencies

- .github/workflows/deploy.yml
- This PR updates the deploy CI to ignore changes to the below-mentioned files
- 'README.md'
- 'LICENSE'
- 'CODE_OF_CONDUCT.md'
- '.vscode/**'
- '.husky/**'
- '.env'
- '.gitignore'
If files apart from the above ones change, then the CI will be triggered.
- This PR also adds a workflow_dispatch trigger in case the deploy fails and the maintainers/admins want to trigger it manually
> [Feat] - Added Ignored Paths to Deploy CI

- docs/develop/c/bpf.md
Add an document page for the `wasm_bpf` plugin, demonstrating how to write programs use the API provided by that plugin
> Add example for `wasm_bpf` plugin

- docs/develop/wasmedge/features.md
This pr removes minor redundancy in this paragraph (https://wasmedge.org/docs/develop/wasmedge/features#cloud-native-orchestration) , as this line has been repeated twice ". If the image is annotated as wasm32, crun will bypass the Linux container setup and use WasmEdge to run the image." This pr removes that .
> Remove minor redundancy in features text

- docs/develop/wasmedge/extensions/proposals.md
This PR removes the WebAssembly GC proposal from the WASI proposal section.
fixes #104 
Documentation
> [Chore] - Remove GC Proposal

- docs/develop/rust/hello_world.md
- docusaurus.config.js
- package-lock.json
> [Chore] - Fixed Code Block Colors

- docs/contribute/source/plugin/wasi_nn.md
- docs/embed/rust/intro.md
Update the content of the `WasmEdge Rust SDK` section to the latest release `0.11.0`
NA
documentation
The latest version of `WasmEdge Rust SDK` has been released. The `intro.md` file should be updated with the info about the latest release.
> [Doc] Update the introduction to `WasmEdge Rust SDK`

- docs/develop/javascript/hello_world.md
- docs/develop/javascript/networking.md
- docs/develop/rust/http_service/client.md
- docs/develop/rust/http_service/server.md
- docs/develop/rust/socket_networking/client.md
- docs/develop/rust/socket_networking/server.md
- docs/start/install.md
Improve the organization and instructions how to best use networking libraries in Rust and JS. Specifically will address HTTPS and TLS use cases.
> Networking related docs update

- .github/workflows/lint.yml
The `prettier` command in CI gives extremely unhelpfully error messages. It simply asks me to run `prettier` without telling me what the actual "style issue" is. 
**I would NOT permit `prettier` to make changes to my writing in any way without first knowing what it thinks the problem is.**
Plus, we already have lint. I think we should remove prettier.
> Remove Prettier

- docs/contribute/source/os/windows.md
- i18n/zh/docusaurus-plugin-content-docs/current/contribute/source/os/windows.md
I'm working on adding support of MSVC for WasmEdge. This adds related docs for this new feature.
See this issue https://github.com/WasmEdge/WasmEdge/issues/2629
See also this PR https://github.com/WasmEdge/WasmEdge/pull/2751
> Add more details for Windows MSVC build process.

- docs/start/install.md
- i18n/zh/docusaurus-plugin-content-docs/current/start/install.md
Starting with WasmEdge v0.13.4, the `wasmedge_rustls_plugin` has been bundled within the WasmEdge core (ref: https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.4). Therefore, this patch modifies the installation instructions for rustls_plugin to indicate that it should be retrieved from the `WasmEdge/WasmEdge` repository, rather than from the `second-state/wasmedge_rustls_plugin`.
This might be related to #108
> Update the installation description for `wasmedge_rustls_plugin`

- docs/embed/c/intro.md
- docs/embed/c/reference/latest.md
In the documentation, the fibonacci.wasm file link leads to 404 page since, Now the directory contains .wat files.
> changed fibonacci.wasm to fibonacci.wat

- docs/start/install.md
- i18n/zh/docusaurus-plugin-content-docs/current/start/install.md
> Update llm inference docs

- docs/start/install.md
Improve the installation instructions, especially around plugins.
> Update install instructions

- docs/develop/deploy/podman.md
Step 3 of https://wasmedge.org/docs/develop/deploy/podman/#prerequisites: It seems like some instructions are missing.
Build and configure crun with WasmEdge support
Next, configure and build a crun binary with WasmEdge support.
Maybe there should be a git clone, similar to https://wasmedge.org/docs/develop/deploy/oci-runtime/crun/#prerequisites
Fixes #195 
Fixes https://github.com/WasmEdge/WasmEdge/issues/3028
Adds the missing git clone in step 3 of https://wasmedge.org/docs/develop/deploy/podman/#prerequisites
Also fixed a typo
> [DOCS]Added missing crun instructions

- src/pages/talks.md
This PR is for the WASM Edge 2023 talks into Documentation 
> kind documentation
In this PR I have added WASM Edge 2023 talks links.
Before 
After
> WASM Edge Talks added

- docs/develop/rust/wasinn/llm_inference.md
1. llama-utils is renamed to llamaedge
2. The links are all broken.
This PR fixed the above issues.
Fixed https://github.com/WasmEdge/WasmEdge/issues/3192
Make things right.
> Fix the outdated llm document

- docs/contribute/source/plugin/rusttls.md
- docs/contribute/source/plugin/wasi_crypto.md
The PR fixes the incorrect link in the plugin documentation.
> Fix the reference link

- docs/contribute/plugin/best_practice.md
- docs/contribute/plugin/test_plugin.md
- i18n/zh/docusaurus-plugin-content-docs/current/contribute/plugin/best_practice.md
- i18n/zh/docusaurus-plugin-content-docs/current/contribute/plugin/test_plugin.md
Added best practice for plugins.
https://github.com/WasmEdge/docs/issues/85
> Add best practices for plugin

- docs/start/build-and-run/docker_wasm_gpu.md
Add a new section to show how to utilize the Container Device Interface (CDI) within a container to enable a WebAssembly (Wasm) application to access GPU devices.
https://github.com/WasmEdge/WasmEdge/issues/3217
documentation
Add new demo section
> Add Docker + Wasm + GPU section

- docs/start/build-and-run/podman_wasm_gpu.md
Add podman execution version (full steps).
None, internal request.
Documentation.
Add other container manager clients support is more user-friendly, especially since support for CDI toolchain is not yet fully mature. This also records a tested and runnable combination for end user.
> Add Podman + Wasm + GPU section

- docs/develop/deploy/kubernetes/knative.md
This PR fixes minor issues with the current knative setup guide. The update is needed to follow the instructions without the issues.
N/A
/kind bug
Fix minor issues
> Update knative instructions

- docs/start/build-and-run/docker_wasm_gpu.md
- docs/start/build-and-run/podman_wasm_gpu.md
The nnpreload and plugin loading mechanisms are already in the upstream.
Replace demo crun source.
https://github.com/WasmEdge/WasmEdge/issues/3217
Documentation
Update repo link
> Update the source for building crun

- docs/develop/rust/database/my_sql_driver.md
- docs/develop/rust/http_service/client.md
- docs/develop/rust/http_service/server.md
- docs/develop/rust/setup.md
- docs/start/install.md
Remove TLS Plugin from install docs
> Remove TLS from install guide

- docs/develop/deploy/oci-runtime/youki.md
Youki changed its build system form make to just.
Both are not really needed to build youki with wasm since you can just run the build script. Updated the instructions and added missing apt packages for wasm like `libzstd-dev`, `curl` and `git`
Does not exist yet
Update the build instructions
> docs: update youki build instructions

- docs/contribute/source/plugin/wasi_nn.md
- docs/start/install.md
I fixed some docs:
- docs/contribute/source/plugin/wasi_nn.md
- fix misplaced Appendix part for ggml backend
- I think the cause is https://github.com/WasmEdge/docs/commit/a2dd6ee153563c8b326d707628aef960e8d26ba1 put the `Build WasmEdge with WASI-NN Neural Speed Backend` part in the wrong place.
- remove duplicate Apple Silicon Model part for ggml backend
- The original has two identical `Apple Silicon Model` parts. One is in the MacOS section after `Intel Model` part and the other is in the Linux section after `General Linux without any acceleration framework` part.
I removed the one in the Linux section after `General Linux without any acceleration framework` part.
- I think this duplicate was removed in [26c0689](https://github.com/WasmEdge/docs/commit/26c068984bbbbec9f67eab5ff741e7b800 …
> fix some docs

- docs/contribute/source/plugin/wasi_nn.md
Add chatTTS install documentation.
[#3547](https://github.com/WasmEdge/WasmEdge/issues/3532)
> [Docs] Add chatTTS backend

- docs/develop/rust/_category_.json
- docs/develop/rust/database/my_sql_driver.md
- docs/develop/rust/database/postgres_driver.md
- docs/develop/rust/database/qdrant_driver.md
- docs/develop/rust/database/redis_driver.md
- docs/develop/rust/http_service/client.md
- docs/develop/rust/http_service/server.md
- docs/develop/rust/setup.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/database/my_sql_driver.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/database/postgres_driver.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/database/qdrant_driver.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/database/redis_driver.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/http_service/client.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/http_service/server.md
- i18n/zh/docusaurus-plugin-content-docs/current/develop/rust/setup.md
Update docs around networking and tokio examples.
> Update tokio examples

- docs/contribute/source/plugin/wasi_nn.md
In this PR, I added a section to show how to setup the dependencies we need for building the ggml plugin on the Windows platform, including how to execute an example.
None.
A new section for the building and execution process.
> Add windows build instructions for the ggml plugin

- docs/develop/deploy/cri-runtime/containerd.md
- docs/develop/deploy/kubernetes/kubernetes-containerd-runwasi.md
Signed-off-by: Shivesh Gupta <shiveshanjaligupta@gmail.com>
- Added docs for running Wasmedge in Kubernetes with containerd-shim-wasmedge using runwasi
- Updated the containerd+runwasi page with a line to run setup script for building runwasi
address #214 
Added instructions for running Wasmedge using runwasi with kubernetes and updated build instruction for runwasi
>  Added docs for Kubernetes+containerd+runwasi setup and updated runwasi setup

- docs/start/install.md
This PR add an install option via nix, so we can get more reports about this installation way.
resolve #248
Add install option
> [Doc] nix install option

- docs/contribute/source/plugin/wasi_nn.md
Add MLX install documentation.
[#3688](https://github.com/WasmEdge/WasmEdge/pull/3688)
> [Docs] Add MLX backend

- docs/develop/rust/hello_world.md
- When marking a code snippet with bash, $ should ideally be ignored.
- Also, the primary purpose should be to guide user `How to run` and output can be omitted.
- Removed the $ in bash code snippets.
- Removed the output of the commands.
> Optimized for clipboard copy action.

- docs/contribute/source/docker.md
- The latest version of Ubuntu supported by WasmEdge was upgraded from 22.04 to 24.04. [WasmEdge#3874]
- Add `manylinux_2_28` as `manylinux2014` was already deprecated. [WasmEdge#3154]
- List images that can be used for plugins development.
[WasmEdge#3874]: https://github.com/WasmEdge/WasmEdge/issues/3847
[WasmEdge#3154]: https://github.com/WasmEdge/WasmEdge/discussions/3154
> Update docker.md (WasmEdge#3874)

- docs/contribute/installer_v2.md
- docs/contribute/overview.md
This PR adds the installer v2 document.
None.
Add a new page for the installer v2
> [Installer] Add the installer v2 documents

- docs/develop/deploy/kubernetes/knative.md
Fixing the incorrect spelling of the word Referring : Refering in this [paragraph](https://wasmedge.org/docs/develop/deploy/kubernetes/knative/#creating-a-cluster-with-kubeadm)
> Fix typo in the page knative.md

- .github/CODEOWNERS
I would like to add the CODEOWNER file so the GitHub will automatically assign the reviewers for the docs PRs.
None.
> misc: Add CODEOWNER for automatically assigning the reviewers

- docs/contribute/users.md
The contribution now has a network name "Xahau".
> Update `XRPL-Labs` Contribution

- docs/contribute/source/plugin/wasi_nn.md
- docs/start/install.md
- i18n/zh/docusaurus-plugin-content-docs/current/contribute/source/plugin/wasi_nn.md
- i18n/zh/docusaurus-plugin-content-docs/current/start/install.md
We no longer provide the prebuilt OpenBLAS version of the llama.cpp plugin.
Remove related sections.
> docs: no longer provide prebuilt blas version of llama.cpp plugin

- docs/contribute/contribute.md
WasmEdge/WasmEdge#3850 introduced conventional commit.
N/A
> docs: explain conventional commit in contribute.md

- docs/contribute/source/os/macos.md
This PR updates the outdated macOS build instructions page to reflect the current LLVM installation path used via Homebrew (llvm@16) and removes a deprecated section Known issues (since the issue has been resolved and there are no currently known issues).
None
While working on a separate PR, I noticed that the macOS build instructions were outdated and caused build failures. Specifically, the current instructions rely on `brew install llvm`, which now installs LLVM 20 by default. LLVM 20 has a different header structure especially for `lld`which breaks the build with errors like:
```
fatal error: 'lld/Common/Driver.h' file not found
```
To fix this, users would need to install `lld` separately and manually update include paths, which complicates the setup. However, using `llvm@16` avoids …
> (docs): update outdated macos build from source docs

- docs/contribute/source/os/android/apk.md
Fixes https://github.com/WasmEdge/WasmEdge/issues/2931
https://github.com/WasmEdge/WasmEdge/issues/2931
> docs(android): add a note about how to get the wasm file from a wat text format

- docs/contribute/source/os/windows.md
The current Windows build instructions for WasmEdge recommend using the curl -sLO command to download LLVM. However, this command fails in PowerShell because Windows aliases curl to PowerShell's Invoke-WebRequest, which does not support the -sLO flags. This PR updates the instructions with a PowerShell-compatible command to ensure smooth downloads on Windows, improving the developer experience.
Closes: https://github.com/WasmEdge/www/issues/31
- Replaced the curl -sLO command in Windows build instructions with a PowerShell-compatible Invoke-WebRequest command.
> fix(docs): replace curl command with PowerShell-compatible Invoke-WebRequest

- docs/contribute/source/plugin/wasi_nn.md
I am working on adding support for BitNet (https://github.com/WasmEdge/WasmEdge/issues/4161).
This PR adds documentation for building BitNet plugin.
Blocked by: https://github.com/WasmEdge/WasmEdge/pull/4253
https://github.com/WasmEdge/WasmEdge/issues/4161
> docs(wasi-nn): add BitNet backend
